plugins {
    id 'com.android.library'
}

android {
    namespace 'dev.flareframework.extensions.community'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        minSdk 24
        targetSdk 36
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation project(':flareclient')
    implementation 'androidx.appcompat:appcompat:1.6.1'
}